server:
  port: 8787
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dzl_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

#阿里云oss，不同的服务器，地址不同
aliyun:
  oss:
    file:
      endponint: xxx
      keyid: xxx
      keysecret: xxx
      bucketname: dzl-xxx

